"use client";

import { useState } from "react";

export interface YieldRiskDisclosureProps {
  /** Callback when user acknowledges the disclosure */
  onAcknowledge: () => void;
  /** Callback when user declines */
  onDecline: () => void;
  /** Optional loading state during acknowledgment */
  isLoading?: boolean;
}

/**
 * Risk disclosure modal shown before first-time yield opt-in.
 * Covers: non-custodial contract risk, strategy risk, and that yield is not guaranteed.
 */
export default function YieldRiskDisclosure({
  onAcknowledge,
  onDecline,
  isLoading = false,
}: YieldRiskDisclosureProps) {
  const [acknowledged, setAcknowledged] = useState(false);

  const handleAcknowledge = () => {
    if (acknowledged && !isLoading) {
      onAcknowledge();
    }
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"
      role="dialog"
      aria-modal="true"
      aria-labelledby="risk-disclosure-title"
    >
      <article className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl border border-border bg-card p-6">
        <header className="mb-6">
          <div className="mb-2 flex h-12 w-12 items-center justify-center rounded-full bg-red-100">
            <svg
              className="h-6 w-6 text-red-600"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              aria-hidden="true"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"
              />
            </svg>
          </div>
          <h2
            id="risk-disclosure-title"
            className="text-xl font-semibold text-foreground"
          >
            Important Risk Disclosure
          </h2>
          <p className="mt-1 text-sm text-muted">
            Please read carefully before enabling yield
          </p>
        </header>

        <section className="space-y-4">
          <div className="rounded-lg border border-border bg-background p-4">
            <h3 className="flex items-center gap-2 text-sm font-semibold text-foreground">
              <svg
                className="h-5 w-5 text-brand"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                aria-hidden="true"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z"
                />
              </svg>
              Non-Custodial Contract Risk
            </h3>
            <p className="mt-2 text-sm text-muted">
              When you enable yield, your funds are deposited into a
              non-custodial smart contract. While your principal is protected,
              the contract operates autonomously—you cannot reverse transactions
              or cancel deposits once submitted.
            </p>
          </div>

          <div className="rounded-lg border border-border bg-background p-4">
            <h3 className="flex items-center gap-2 text-sm font-semibold text-foreground">
              <svg
                className="h-5 w-5 text-brand"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                aria-hidden="true"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M13 10V3L4 14h7v7l9-11h-7z"
                />
              </svg>
              Strategy Risk
            </h3>
            <p className="mt-2 text-sm text-muted">
              Yield is generated by routing your funds to an external strategy
              contract (e.g., a lending protocol). The adapter does not verify
              the strategy&apos;s solvency or correctness—it relies on the
              strategy&apos;s reported balance. A malicious or buggy strategy
              could misreport yield or lose funds. Admin can change the active
              strategy at any time.
            </p>
          </div>

          <div className="rounded-lg border border-border bg-background p-4">
            <h3 className="flex items-center gap-2 text-sm font-semibold text-foreground">
              <svg
                className="h-5 w-5 text-brand"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                aria-hidden="true"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                />
              </svg>
              Yield Is Not Guaranteed
            </h3>
            <p className="mt-2 text-sm text-muted">
              Past performance does not guarantee future results. The strategy
              may generate yield, losses, or nothing at all. Your returns depend
              on the strategy&apos;s performance, and you may receive less than
              your original deposit.
            </p>
          </div>

          <div className="rounded-lg border border-red-200 bg-red-50 p-4">
            <p className="text-xs font-medium text-red-800">
              By proceeding, you acknowledge that you have read, understood,
              and agree to assume these risks.
            </p>
          </div>
        </section>

        <div className="mt-6">
          <label className="flex items-start gap-3 cursor-pointer">
            <input
              type="checkbox"
              checked={acknowledged}
              onChange={(e) => setAcknowledged(e.target.checked)}
              className="mt-1 h-4 w-4 rounded border-border text-brand focus:ring-brand"
            />
            <span className="text-sm text-foreground">
              I have read and understand the risks described above
            </span>
          </label>
        </div>

        <div className="mt-6 flex gap-3 border-t border-border pt-4">
          <button
            onClick={onDecline}
            disabled={isLoading}
            className="flex-1 rounded-lg border border-border bg-background px-4 py-2.5 text-sm font-medium text-foreground transition-colors hover:bg-muted disabled:opacity-50 disabled:cursor-not-allowed"
            aria-label="Decline and go back"
          >
            Cancel
          </button>
          <button
            onClick={handleAcknowledge}
            disabled={!acknowledged || isLoading}
            className="flex-1 rounded-lg bg-brand px-4 py-2.5 text-sm font-medium text-white transition-colors hover:bg-brand/90 disabled:cursor-not-allowed disabled:opacity-50"
            aria-label="Acknowledge and continue"
          >
            {isLoading ? "Processing..." : "I Understand, Continue"}
          </button>
        </div>

        {isLoading && (
          <p
            className="mt-3 text-center text-xs text-muted"
            role="status"
            aria-live="polite"
          >
            Processing your request...
          </p>
        )}
      </article>
    </div>
  );
}